-- ReCognate Web Application - Supabase Schema & RLS Policies

-- 1. Create Tables
CREATE TABLE IF NOT EXISTS team_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  expertise TEXT NOT NULL,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  description TEXT NOT NULL,
  technologies TEXT[] DEFAULT '{}',
  status TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  subtitle TEXT NOT NULL,
  description TEXT NOT NULL,
  status TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS rd_prototypes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  status TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE rd_prototypes ENABLE ROW LEVEL SECURITY;

-- 3. Grant Table Permissions
-- This is necessary to fix "permission denied for table" errors
GRANT ALL ON TABLE team_members TO anon, authenticated, service_role;
GRANT ALL ON TABLE projects TO anon, authenticated, service_role;
GRANT ALL ON TABLE products TO anon, authenticated, service_role;
GRANT ALL ON TABLE rd_prototypes TO anon, authenticated, service_role;


-- 4. Create RLS Policies

-- Drop existing policies first to allow re-running the script
DROP POLICY IF EXISTS "Allow public read access to team_members" ON team_members;
DROP POLICY IF EXISTS "Allow public read access to projects" ON projects;
DROP POLICY IF EXISTS "Allow public read access to products" ON products;
DROP POLICY IF EXISTS "Allow public read access to rd_prototypes" ON rd_prototypes;

DROP POLICY IF EXISTS "Allow public insert to team_members" ON team_members;
DROP POLICY IF EXISTS "Allow public update to team_members" ON team_members;
DROP POLICY IF EXISTS "Allow public delete to team_members" ON team_members;

DROP POLICY IF EXISTS "Allow public insert to projects" ON projects;
DROP POLICY IF EXISTS "Allow public update to projects" ON projects;
DROP POLICY IF EXISTS "Allow public delete to projects" ON projects;

DROP POLICY IF EXISTS "Allow public insert to products" ON products;
DROP POLICY IF EXISTS "Allow public update to products" ON products;
DROP POLICY IF EXISTS "Allow public delete to products" ON products;

DROP POLICY IF EXISTS "Allow public insert to rd_prototypes" ON rd_prototypes;
DROP POLICY IF EXISTS "Allow public update to rd_prototypes" ON rd_prototypes;
DROP POLICY IF EXISTS "Allow public delete to rd_prototypes" ON rd_prototypes;

-- Public Read Access: Allow anyone (anon) to read data
CREATE POLICY "Allow public read access to team_members" ON team_members FOR SELECT USING (true);
CREATE POLICY "Allow public read access to projects" ON projects FOR SELECT USING (true);
CREATE POLICY "Allow public read access to products" ON products FOR SELECT USING (true);
CREATE POLICY "Allow public read access to rd_prototypes" ON rd_prototypes FOR SELECT USING (true);

-- Admin Write Access: Allow anyone (for demo/development purposes) to insert, update, and delete
-- WARNING: In a real production app, replace 'true' with 'auth.role() = ''authenticated''' to restrict to logged-in users.
CREATE POLICY "Allow public insert to team_members" ON team_members FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update to team_members" ON team_members FOR UPDATE USING (true);
CREATE POLICY "Allow public delete to team_members" ON team_members FOR DELETE USING (true);

CREATE POLICY "Allow public insert to projects" ON projects FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update to projects" ON projects FOR UPDATE USING (true);
CREATE POLICY "Allow public delete to projects" ON projects FOR DELETE USING (true);

CREATE POLICY "Allow public insert to products" ON products FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update to products" ON products FOR UPDATE USING (true);
CREATE POLICY "Allow public delete to products" ON products FOR DELETE USING (true);

CREATE POLICY "Allow public insert to rd_prototypes" ON rd_prototypes FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update to rd_prototypes" ON rd_prototypes FOR UPDATE USING (true);
CREATE POLICY "Allow public delete to rd_prototypes" ON rd_prototypes FOR DELETE USING (true);

-- You can now run `node migrate-data.mjs` to seed the database safely.

-- ==========================================
-- 5. Jobs (Careers) Table
-- ==========================================
CREATE TABLE IF NOT EXISTS jobs (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    title TEXT NOT NULL,
    department TEXT NOT NULL,
    location TEXT NOT NULL,
    type TEXT NOT NULL,
    description TEXT NOT NULL,
    requirements TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS for jobs
ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;

-- Grant permissions to fix "permission denied"
GRANT ALL ON TABLE jobs TO anon, authenticated, service_role;

-- Drop existing policies first
DROP POLICY IF EXISTS "Allow public read access to jobs" ON jobs;
DROP POLICY IF EXISTS "Allow public insert to jobs" ON jobs;
DROP POLICY IF EXISTS "Allow public update to jobs" ON jobs;
DROP POLICY IF EXISTS "Allow public delete to jobs" ON jobs;

-- Allow public read access to jobs
CREATE POLICY "Allow public read access to jobs" ON jobs FOR SELECT USING (true);

-- Allow public insert, update, delete for demo/development purposes
CREATE POLICY "Allow public insert to jobs" ON jobs FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update to jobs" ON jobs FOR UPDATE USING (true);
CREATE POLICY "Allow public delete to jobs" ON jobs FOR DELETE USING (true);

-- ==========================================
-- 6. Storage Buckets (Images)
-- ==========================================
-- Create the storage bucket
INSERT INTO storage.buckets (id, name, public) VALUES ('images', 'images', true) ON CONFLICT (id) DO NOTHING;

-- Storage Policies
-- Drop existing policies first
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
DROP POLICY IF EXISTS "Public Upload" ON storage.objects;
DROP POLICY IF EXISTS "Public Update" ON storage.objects;
DROP POLICY IF EXISTS "Public Delete" ON storage.objects;

-- Allow public access to view images
CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'images');

-- Allow anon and authenticated users to upload images
CREATE POLICY "Public Upload" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'images');

-- Allow users to update their images
CREATE POLICY "Public Update" ON storage.objects FOR UPDATE USING (bucket_id = 'images');

-- Allow users to delete their images
CREATE POLICY "Public Delete" ON storage.objects FOR DELETE USING (bucket_id = 'images');

-- ==========================================
-- 7. Job Applications Table
-- ==========================================
CREATE TABLE IF NOT EXISTS job_applications (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    job_id UUID REFERENCES jobs(id) ON DELETE SET NULL,
    job_title TEXT NOT NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    resume_url TEXT NOT NULL,
    message TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS for job_applications
ALTER TABLE job_applications ENABLE ROW LEVEL SECURITY;

-- Grant permissions to fix "permission denied"
GRANT ALL ON TABLE job_applications TO anon, authenticated, service_role;

-- Drop existing policies first
DROP POLICY IF EXISTS "Allow public read access to job_applications" ON job_applications;
DROP POLICY IF EXISTS "Allow public insert to job_applications" ON job_applications;
DROP POLICY IF EXISTS "Allow public update to job_applications" ON job_applications;
DROP POLICY IF EXISTS "Allow public delete to job_applications" ON job_applications;

-- Allow public read access to job_applications
CREATE POLICY "Allow public read access to job_applications" ON job_applications FOR SELECT USING (true);

-- Allow public insert, update, delete for demo/development purposes
CREATE POLICY "Allow public insert to job_applications" ON job_applications FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update to job_applications" ON job_applications FOR UPDATE USING (true);
CREATE POLICY "Allow public delete to job_applications" ON job_applications FOR DELETE USING (true);

-- ==========================================
-- 8. Contact Requests (Inquiries) Table
-- ==========================================
CREATE TABLE IF NOT EXISTS contact_requests (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    company TEXT,
    category TEXT,
    timeline TEXT,
    description TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS for contact_requests
ALTER TABLE contact_requests ENABLE ROW LEVEL SECURITY;

-- Grant permissions to fix "permission denied"
GRANT ALL ON TABLE contact_requests TO anon, authenticated, service_role;

-- Drop existing policies first
DROP POLICY IF EXISTS "Allow public read access to contact_requests" ON contact_requests;
DROP POLICY IF EXISTS "Allow public insert to contact_requests" ON contact_requests;
DROP POLICY IF EXISTS "Allow public update to contact_requests" ON contact_requests;
DROP POLICY IF EXISTS "Allow public delete to contact_requests" ON contact_requests;

-- Allow public read access to contact_requests
CREATE POLICY "Allow public read access to contact_requests" ON contact_requests FOR SELECT USING (true);

-- Allow public insert, update, delete for demo/development purposes
CREATE POLICY "Allow public insert to contact_requests" ON contact_requests FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update to contact_requests" ON contact_requests FOR UPDATE USING (true);
CREATE POLICY "Allow public delete to contact_requests" ON contact_requests FOR DELETE USING (true);
