-- Run this in your Supabase SQL Editor to create the table

CREATE TABLE public.academic_projects (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  description text not null,
  technologies text[] null,
  price text null,
  "hasReport" boolean default false,
  "hasPresentation" boolean default false,
  "hasCode" boolean default false,
  features text[] null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Note: Ensure Row Level Security (RLS) is configured appropriately. 
-- For testing, you can temporarily disable it or add a policy allowing public read access.
-- ALTER TABLE public.academic_projects ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Enable read access for all users" ON public.academic_projects FOR SELECT USING (true);
