-- Run this entire script in the Supabase SQL Editor to prepare your database.

-- 1. TEAM MEMBERS
CREATE TABLE IF NOT EXISTS public.team_members (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  expertise text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable public read access" ON public.team_members FOR SELECT USING (true);
CREATE POLICY "Enable public insert access" ON public.team_members FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable public update access" ON public.team_members FOR UPDATE USING (true);
CREATE POLICY "Enable public delete access" ON public.team_members FOR DELETE USING (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.team_members TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.team_members TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.team_members TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.team_members_id_seq TO anon;
GRANT USAGE, SELECT ON SEQUENCE public.team_members_id_seq TO authenticated;


-- 2. PROJECTS
CREATE TABLE IF NOT EXISTS public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  description text not null,
  technologies text[] null,
  status text not null,
  client text not null,
  url text null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable public read access" ON public.projects FOR SELECT USING (true);
CREATE POLICY "Enable public insert access" ON public.projects FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable public update access" ON public.projects FOR UPDATE USING (true);
CREATE POLICY "Enable public delete access" ON public.projects FOR DELETE USING (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.projects TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.projects TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.projects TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.projects_id_seq TO anon;
GRANT USAGE, SELECT ON SEQUENCE public.projects_id_seq TO authenticated;


-- 3. PRODUCTS
CREATE TABLE IF NOT EXISTS public.products (
  id text primary key,
  name text not null,
  subtitle text not null,
  description text not null,
  features text[] null,
  color text default 'blue' not null,
  status text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable public read access" ON public.products FOR SELECT USING (true);
CREATE POLICY "Enable public insert access" ON public.products FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable public update access" ON public.products FOR UPDATE USING (true);
CREATE POLICY "Enable public delete access" ON public.products FOR DELETE USING (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.products TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.products TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.products TO service_role;


-- 4. R&D INITIATIVES (Prototypes)
CREATE TABLE IF NOT EXISTS public.rd_prototypes (
  id bigint generated by default as identity primary key,
  title text not null,
  icon_name text not null,
  color text default 'blue' not null,
  description text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.rd_prototypes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable public read access" ON public.rd_prototypes FOR SELECT USING (true);
CREATE POLICY "Enable public insert access" ON public.rd_prototypes FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable public update access" ON public.rd_prototypes FOR UPDATE USING (true);
CREATE POLICY "Enable public delete access" ON public.rd_prototypes FOR DELETE USING (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.rd_prototypes TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.rd_prototypes TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.rd_prototypes TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.rd_prototypes_id_seq TO anon;
GRANT USAGE, SELECT ON SEQUENCE public.rd_prototypes_id_seq TO authenticated;


-- 5. JOB POSTINGS (Careers)
CREATE TABLE IF NOT EXISTS public.job_postings (
  id text primary key,
  title text not null,
  department text not null,
  location text not null,
  type text not null,
  description text not null,
  requirements text[] null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.job_postings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable public read access" ON public.job_postings FOR SELECT USING (true);
CREATE POLICY "Enable public insert access" ON public.job_postings FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable public update access" ON public.job_postings FOR UPDATE USING (true);
CREATE POLICY "Enable public delete access" ON public.job_postings FOR DELETE USING (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.job_postings TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.job_postings TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.job_postings TO service_role;
